/**
 * EAS/SAME lookup tables for human-readable interpretation.
 */

export const ORIGINATOR_CODES = {
  EAS: "Emergency Alert System Participant",
  CIV: "Civil Authorities",
  WXR: "National Weather Service",
  PEP: "Primary Entry Point System",
};

export const EVENT_CODES = {
  // National
  EAN: "Emergency Action Notification",
  NIC: "National Information Center",
  NPT: "National Periodic Test",
  NMN: "National Message Notification",
  RMT: "Required Monthly Test",
  RWT: "Required Weekly Test",

  // Weather — warnings
  TOR: "Tornado Warning",
  SVR: "Severe Thunderstorm Warning",
  FFW: "Flash Flood Warning",
  FLW: "Flood Warning",
  SMW: "Special Marine Warning",
  SVS: "Severe Weather Statement",
  SPS: "Special Weather Statement",
  BZW: "Blizzard Warning",
  WSW: "Winter Storm Warning",
  EWW: "Extreme Wind Warning",
  HUW: "Hurricane Warning",
  HUA: "Hurricane Watch",
  HLS: "Hurricane Statement",
  TSW: "Tsunami Warning",
  TSA: "Tsunami Watch",
  DSW: "Dust Storm Warning",
  SQW: "Snow Squall Warning",

  // Weather — watches
  TOA: "Tornado Watch",
  SVA: "Severe Thunderstorm Watch",
  FFA: "Flash Flood Watch",
  FLA: "Flood Watch",
  WSA: "Winter Storm Watch",

  // Weather — advisories
  WCW: "Wind Chill Warning",
  HWW: "High Wind Warning",
  HWA: "High Wind Watch",
  FRW: "Fire Warning",
  CFW: "Coastal Flood Warning",
  CFA: "Coastal Flood Watch",

  // Civil
  CEM: "Civil Emergency Message",
  ADR: "Administrative Message",
  CAE: "Child Abduction Emergency",
  LAE: "Local Area Emergency",
  CDW: "Civil Danger Warning",
  EVI: "Evacuation Immediate",
  SPW: "Shelter in Place Warning",
  LEW: "Law Enforcement Warning",
  BLU: "Blue Alert",
  NUW: "Nuclear Power Plant Warning",
  RHW: "Radiological Hazard Warning",
  VOW: "Volcano Warning",
  AVW: "Avalanche Warning",
  AVA: "Avalanche Watch",
  EQW: "Earthquake Warning",
  FRW: "Fire Warning",

  // Practice/test
  DMO: "Practice/Demo Warning",
  PEV: "Potential Evacuation",

  // AMBER
  AMB: "AMBER Alert",
};

export const STATE_FIPS = {
  "00": "All States",
  "01": "Alabama",
  "02": "Alaska",
  "04": "Arizona",
  "05": "Arkansas",
  "06": "California",
  "08": "Colorado",
  "09": "Connecticut",
  10: "Delaware",
  11: "District of Columbia",
  12: "Florida",
  13: "Georgia",
  15: "Hawaii",
  16: "Idaho",
  17: "Illinois",
  18: "Indiana",
  19: "Iowa",
  20: "Kansas",
  21: "Kentucky",
  22: "Louisiana",
  23: "Maine",
  24: "Maryland",
  25: "Massachusetts",
  26: "Michigan",
  27: "Minnesota",
  28: "Mississippi",
  29: "Missouri",
  30: "Montana",
  31: "Nebraska",
  32: "Nevada",
  33: "New Hampshire",
  34: "New Jersey",
  35: "New Mexico",
  36: "New York",
  37: "North Carolina",
  38: "North Dakota",
  39: "Ohio",
  40: "Oklahoma",
  41: "Oregon",
  42: "Pennsylvania",
  44: "Rhode Island",
  45: "South Carolina",
  46: "South Dakota",
  47: "Tennessee",
  48: "Texas",
  49: "Utah",
  50: "Vermont",
  51: "Virginia",
  53: "Washington",
  54: "West Virginia",
  55: "Wisconsin",
  56: "Wyoming",
  // Territories
  60: "American Samoa",
  66: "Guam",
  69: "Northern Mariana Islands",
  72: "Puerto Rico",
  78: "U.S. Virgin Islands",
};
